version: '3.7'

volumes:
  logs:
    driver: local

services:
  slim:
    build:
      context: .
      target: development
      args:
        UID: ${UID:-502}
    ports:
      - 80:80
    volumes:
      - .:/var/www
